# Generated by Django 2.2 on 2021-10-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_account_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_online',
            field=models.IntegerField(default=0),
        ),
    ]
