# Generated by Django 2.2 on 2021-10-31 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20211028_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiseANiveau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachement', models.ImageField(upload_to='preuves')),
                ('attributed', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('aucun', 'Aucun'), ('secure', 'Sécurisé'), ('online_seller', 'Vendeur en ligne'), ('kid', 'Enfant'), ('ado', 'Adolescent'), ('entreprise', 'Entreprise'), ('special_needs', 'Besoins spéciaux')], max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
