# Generated by Django 2.2 on 2021-10-31 22:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_miseaniveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='miseaniveau',
            name='date_attribution',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='miseaniveau',
            name='duree',
            field=models.CharField(choices=[(1, '1 Mois'), (3, '3 Mois'), (6, '6 Mois'), (12, '12 Mois')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
