# Generated by Django 2.2 on 2021-10-31 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20211031_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miseaniveau',
            name='duree',
            field=models.CharField(choices=[('1', '1 Mois'), ('3', '3 Mois'), ('6', '6 Mois'), ('12', '12 Mois')], max_length=5),
        ),
    ]
