# Generated by Django 2.2 on 2021-11-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_account_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='miseaniveau',
            name='NIN',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
