# Generated by Django 2.2 on 2022-02-17 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20220211_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='identite_confirme',
            field=models.BooleanField(default=False),
        ),
    ]
