# Generated by Django 2.2 on 2022-02-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_account_identite_confirme'),
    ]

    operations = [
        migrations.AddField(
            model_name='miseaniveau',
            name='adresse',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='miseaniveau',
            name='code_confirmation',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
    ]
