# Generated by Django 2.2 on 2021-05-12 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210511_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='slug',
            field=models.CharField(default='', max_length=256),
        ),
    ]
