# Generated by Django 2.2 on 2021-05-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_annonce_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='slug',
            field=models.CharField(default='', max_length=256, unique=True),
        ),
    ]
