# Generated by Django 2.2 on 2021-05-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_signal'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='raison',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
