# Generated by Django 2.2 on 2021-05-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_demandecontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='categorie',
            field=models.CharField(default='', max_length=256),
        ),
    ]
