# Generated by Django 2.2 on 2021-06-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210622_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='sous_categorie',
            field=models.CharField(default='', max_length=256),
        ),
    ]
