# Generated by Django 2.2 on 2021-07-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_annonce_sous_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='useruploads')),
            ],
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='img5',
        ),
        migrations.AddField(
            model_name='annonce',
            name='images',
            field=models.ManyToManyField(to='core.PostImages'),
        ),
    ]
