# Generated by Django 2.2 on 2021-11-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_arnaque'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='notice',
            field=models.CharField(default='', max_length=256),
        ),
    ]
