# Generated by Django 2.2 on 2021-11-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_annonce_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='age_max',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annonce',
            name='age_min',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annonce',
            name='sexe',
            field=models.CharField(choices=[('f', 'Femelle'), ('m', 'Male')], default='m', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annonce',
            name='wilaya',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
