# Generated by Django 2.2 on 2021-11-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20211104_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='sexe',
            field=models.CharField(choices=[('both', 'Les deux'), ('f', 'Femelle'), ('m', 'Male')], max_length=1),
        ),
    ]
