# Generated by Django 2.2 on 2021-11-08 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0020_auto_20211104_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Annonce')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='AnnonceArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256)),
                ('categorie', models.CharField(choices=[('Téléphones', 'Téléphones'), ('Véhicules', 'Véhicules'), ('Immobilier', 'Immobilier'), ('Electronique & Electroménager', 'Electronique & Electroménager'), ('Emploi', 'Emploi'), ('Informatique', 'Informatique'), ('Mode & Beauté', 'Mode & Beauté'), ('Maison & Fournitures', 'Maison & Fournitures'), ('Loisirs & Divertissements', 'Loisirs & Divertissements'), ('Matériaux & Equipement', 'Matériaux & Equipement'), ('Voyages', 'Voyages'), ('Services', 'Services'), ('Divers', 'Divers')], max_length=256)),
                ('sous_categorie', models.CharField(default='', max_length=256)),
                ('slug', models.CharField(default='', max_length=256, unique=True)),
                ('description', models.TextField()),
                ('notice', models.CharField(default='', max_length=256)),
                ('prix', models.IntegerField()),
                ('typeannonce', models.CharField(choices=[('achat', 'Achat'), ('vente', 'Vente'), ('urgence', 'Urgence'), ('covoiturage', 'Covoiturage')], max_length=256)),
                ('sexe', models.CharField(choices=[('both', 'Les deux'), ('f', 'Femelle'), ('m', 'Male')], max_length=1)),
                ('age_min', models.IntegerField()),
                ('age_max', models.IntegerField()),
                ('wilaya', models.CharField(choices=[('Adrar', 'Adrar'), ('Chlef', 'Chlef'), ('Laghouat', 'Laghouat'), ('Oum El Bouaghi', 'Oum El Bouaghi'), ('Batna', 'Batna'), ('Béjaïa', 'Béjaïa'), ('Biskra', 'Biskra'), ('Béchar', 'Béchar'), ('Blida', 'Blida'), ('Bouira', 'Bouira'), ('Tamanrasset', 'Tamanrasset'), ('Tébessa', 'Tébessa'), ('Tlemcen', 'Tlemcen'), ('Tiaret', 'Tiaret'), ('Tizi Ouzou', 'Tizi Ouzou'), ('Alger', 'Alger'), ('Djelfa', 'Djelfa'), ('Jijel', 'Jijel'), ('Sétif', 'Sétif'), ('Saïda', 'Saïda'), ('Skikda', 'Skikda'), ('Sidi Bel Abbès', 'Sidi Bel Abbès'), ('Annaba', 'Annaba'), ('Guelma', 'Guelma'), ('Constantine', 'Constantine'), ('Médéa', 'Médéa'), ('Mostaganem', 'Mostaganem'), ("M'Sila", "M'Sila"), ('Mascara', 'Mascara'), ('Ouargla', 'Ouargla'), ('Oran', 'Oran'), ('El Bayadh', 'El Bayadh'), ('Illizi', 'Illizi'), ('Bordj Bou Arreridj', 'Bordj Bou Arreridj'), ('Boumerdès', 'Boumerdès'), ('El Tarf', 'El Tarf'), ('Tindouf', 'Tindouf'), ('Tissemsilt', 'Tissemsilt'), ('El Oued', 'El Oued'), ('Khenchela', 'Khenchela'), ('Souk Ahras', 'Souk Ahras'), ('Tipaza', 'Tipaza'), ('Mila', 'Mila'), ('Aïn Defla', 'Aïn Defla'), ('Naâma', 'Naâma'), ('Aïn Témouchent', 'Aïn Témouchent'), ('Ghardaïa', 'Ghardaïa'), ('Relizane', 'Relizane')], max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(to='core.PostImages')),
            ],
        ),
    ]
