# Generated by Django 2.2 on 2021-11-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_annoncearchive_deleterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='buyer',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='annoncearchive',
            name='buyer',
            field=models.CharField(default='', max_length=256),
        ),
    ]
