# Generated by Django 2.2 on 2022-02-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_historyitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='vendeur_en_ligne',
            field=models.BooleanField(default=False),
        ),
    ]
