# Generated by Django 2.2 on 2022-02-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_annonce_vendeur_en_ligne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='images',
            field=models.ManyToManyField(blank=True, to='core.PostImages'),
        ),
    ]
