# Generated by Django 2.2 on 2022-02-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20220217_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='sexe',
            field=models.CharField(choices=[('both', 'Les deux'), ('f', 'Femme'), ('h', 'Homme')], max_length=1),
        ),
        migrations.AlterField(
            model_name='annoncearchive',
            name='sexe',
            field=models.CharField(choices=[('both', 'Les deux'), ('f', 'Femme'), ('h', 'Homme')], max_length=1),
        ),
    ]
