# Generated by Django 2.2 on 2022-02-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20220219_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='buyer',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
