# Generated by Django 2.2 on 2021-10-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_auto_20211027_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='creator_seen',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='chat',
            name='receiver_seen',
            field=models.BooleanField(default=1),
        ),
    ]
